# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, help_text='Category Display Name', max_length=150)),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Narrative overview of this taxonomy classification', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='Material vector icon or illustration URI', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle public visibility across customer and vendor apps')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort hierarchy order on Customer App Home Dashboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category for nested taxonomy hierarchies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='categories.category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
