from django.db import models
from django.conf import settings
from apps.business.models import BusinessProfile

class ListingPlan(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=10, default="INR")
    duration_days = models.PositiveIntegerField(help_text="Duration in days")
    is_active = models.BooleanField(default=True)
    display_order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['display_order', 'price']

    def __str__(self):
        return f"{self.name} - {self.price} ({self.duration_days} days)"


class VendorSubscription(models.Model):
    STATUS_CHOICES = (
        ('PENDING', 'Pending'),
        ('ACTIVE', 'Active'),
        ('EXPIRED', 'Expired'),
        ('CANCELLED', 'Cancelled'),
        ('PAYMENT_FAILED', 'Payment Failed'),
    )

    vendor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='subscriptions')
    store = models.ForeignKey(BusinessProfile, on_delete=models.CASCADE, related_name='subscriptions')
    plan = models.ForeignKey(ListingPlan, on_delete=models.SET_NULL, null=True, related_name='subscriptions')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=10, default="INR")

    transaction_id = models.CharField(max_length=100, blank=True, null=True, help_text="Unique transaction ID from provider")
    provider_payment_id = models.CharField(max_length=100, blank=True, null=True)
    signature = models.CharField(max_length=200, blank=True, null=True)
    payment_provider = models.CharField(max_length=50, default='DUMMY', help_text="Payment gateway provider")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.store.business_name} - {self.plan.name if self.plan else 'Unknown'} ({self.status})"


class PaymentRecord(models.Model):
    STATUS_CHOICES = (
        ('PENDING', 'Pending'),
        ('SUCCESS', 'Success'),
        ('FAILED', 'Failed'),
    )

    vendor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='payments')
    store = models.ForeignKey(BusinessProfile, on_delete=models.CASCADE, related_name='payments')
    subscription = models.ForeignKey(VendorSubscription, on_delete=models.CASCADE, related_name='payments')
    plan = models.ForeignKey(ListingPlan, on_delete=models.SET_NULL, null=True, related_name='payments')
    
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=10, default="INR")
    
    transaction_id = models.CharField(max_length=100, blank=True, null=True, help_text="Unique transaction ID generated by backend or gateway")
    provider_payment_id = models.CharField(max_length=100, blank=True, null=True, help_text="Payment ID returned by the provider")
    payment_provider = models.CharField(max_length=50, default='DUMMY', help_text="Payment gateway provider (e.g., RAZORPAY, STRIPE, DUMMY)")
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    
    created_at = models.DateTimeField(auto_now_add=True)
    verified_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Payment {self.id} for {self.store.business_name} - {self.status}"
