# Generated by Django 6.0.7 on 2026-07-31 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Headline e.g. Studio Onboarding Approved!', max_length=200)),
                ('message', models.TextField(help_text='Full narrative message body')),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'Platform System Message'), ('ONBOARDING', 'Studio Onboarding & Governance'), ('REVIEW', 'Customer Review & Rating Alert'), ('PROMOTION', 'Promotional Offer & Discount Campaign'), ('SECURITY', 'Authentication & Security Alert')], db_index=True, default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Tracks read/unread state for UI badges')),
                ('action_url', models.CharField(blank=True, help_text='Optional internal navigation deep link e.g. /vendor/profile or /store/details/<id>', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User account targeted by this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
