# Generated by Django 6.0.7 on 2026-07-31 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_name', models.CharField(help_text='Full legal name of primary business owner', max_length=150)),
                ('official_email', models.EmailField(help_text='Business communication email address', max_length=254)),
                ('phone_number', models.CharField(db_index=True, help_text='Primary contact telephone', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('APPROVED', 'Verified & Approved'), ('REJECTED', 'Application Rejected'), ('SUSPENDED', 'Temporarily Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Feedback provided by governance admin upon rejection or suspension', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor_studios', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Associated authentication user account (Role: VENDOR)', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('GSTIN', 'GSTIN Tax Registration Certificate'), ('PAN', 'Business / Personal PAN Card'), ('TRADE_LICENSE', 'Shop & Establishment / Trade License'), ('ID_PROOF', 'Owner Government Identity Proof'), ('ADDRESS_PROOF', 'Studio Physical Address Proof')], max_length=50)),
                ('document_url', models.URLField(help_text='Secure storage URI of uploaded file', max_length=500)),
                ('document_number', models.CharField(blank=True, help_text='License or registration identification number', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Accepted'), ('REJECTED', 'Rejected Document')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendor_kyc_files', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
