# Generated by Django 6.0.7 on 2026-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='chat_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], default='ACTIVE', help_text='Administrative override for chat functionality.', max_length=20),
        ),
    ]
