# Generated by Django 6.0.7 on 2026-07-31 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_businessprofile_category'),
        ('catalog', '0002_alter_product_options_product_item_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Studio Confirmation'), ('CONFIRMED', 'Appointment Confirmed'), ('RESCHEDULED', 'Rescheduled by Studio/Client'), ('REJECTED', 'Declined by Studio'), ('CANCELLED', 'Cancelled by Customer'), ('COMPLETED', 'Service Fulfilled & Completed')], db_index=True, default='PENDING', max_length=20)),
                ('customer_notes', models.TextField(blank=True, help_text='Special instructions or style preferences', null=True)),
                ('studio_feedback', models.TextField(blank=True, help_text='Vendor notes upon confirmation or reschedule', null=True)),
                ('business_profile', models.ForeignKey(help_text='Studio hosting the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Target catalog item (must be item_type=SERVICE)', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Appointment Booking',
                'verbose_name_plural': 'Service Appointment Bookings',
                'ordering': ['-appointment_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'New Customer Enquiry'), ('RESPONDED', 'Studio Responded & Quoted'), ('ORDER_PLACED', 'Converted to Bespoke Order'), ('CLOSED', 'Enquiry Closed')], db_index=True, default='OPEN', max_length=20)),
                ('message', models.TextField(help_text='Customer query regarding custom sizing, fabrics, or delivery timelines')),
                ('target_delivery_date', models.DateField(blank=True, help_text='Desired date of custom completion', null=True)),
                ('studio_response', models.TextField(blank=True, help_text='Studio consultation feedback & quote specifics', null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Negotiated custom order price (INR)', max_digits=12, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='business.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Target catalog item (must be item_type=PRODUCT)', on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Enquiry & Bespoke Order',
                'verbose_name_plural': 'Product Enquiries & Bespoke Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSchedule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday to 6=Sunday')),
                ('open_time', models.TimeField(default='10:00:00', help_text='Showroom opening hour')),
                ('close_time', models.TimeField(default='19:00:00', help_text='Showroom closing hour')),
                ('is_closed', models.BooleanField(default=False, help_text='Toggle weekly day-off closure')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60, help_text='Standard booking interval in minutes')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='business.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Operating Schedule',
                'verbose_name_plural': 'Vendor Operating Schedules',
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('business_profile', 'day_of_week'), name='unique_studio_day_schedule')],
            },
        ),
    ]
