# Generated by Django 6.1 on 2026-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorsubscription',
            old_name='razorpay_signature',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='vendorsubscription',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='vendorsubscription',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_provider',
            field=models.CharField(default='DUMMY', help_text='Payment gateway provider (e.g., RAZORPAY, STRIPE, DUMMY)', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='provider_payment_id',
            field=models.CharField(blank=True, help_text='Payment ID returned by the provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction ID generated by backend or gateway', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='payment_provider',
            field=models.CharField(default='DUMMY', help_text='Payment gateway provider', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction ID from provider', max_length=100, null=True),
        ),
    ]
