# Generated by Django 6.0.7 on 2026-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_razorpay_signature_vendorsubscription_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingplan',
            name='customer_chat',
            field=models.BooleanField(default=False, help_text='Entitlement for customer chat'),
        ),
    ]
