# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_businessprofile_category'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(help_text='Cloud Blob Storage URI for showroom imagery', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Short narrative descriptive caption', max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort sequence in showroom gallery carousel')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='business.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Campaign headline e.g. Monsoon Wedding Festival Deal', max_length=150)),
                ('promo_code', models.CharField(blank=True, help_text='Alphanumeric verification voucher code', max_length=50, null=True)),
                ('description', models.TextField(help_text='Terms of promotion and redemption inclusions')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Percentage reduction e.g. 25 for 25% off', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Campaign expiration timestamp', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle promotion active state')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='business.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotional Offer',
                'verbose_name_plural': 'Promotional Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, help_text='Product Title or Collection Name', max_length=200)),
                ('description', models.TextField(help_text='Detailed material, fit, and craftsmanship specifications')),
                ('price', models.DecimalField(decimal_places=2, help_text='Standard showroom retail price (INR)', max_digits=12)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional promotional promotional pricing', max_digits=12, null=True)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In Stock & Available'), ('OUT_OF_STOCK', 'Temporarily Out of Stock'), ('MADE_TO_ORDER', 'Bespoke / Made to Order'), ('PRE_ORDER', 'Pre-Order Collection')], default='IN_STOCK', max_length=30)),
                ('image_url', models.URLField(help_text='Primary high-resolution product photography URI', max_length=500)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Highlight on studio showroom banner')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle public catalog availability')),
                ('business_profile', models.ForeignKey(help_text='Partner studio showroom offering this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.businessprofile')),
                ('category', models.ForeignKey(blank=True, help_text='Taxonomy classification for structured O2O search', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
