# Generated by Django 6.0.7 on 2026-07-31 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessprofile_category'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Catalog Item (Product / Service)', 'verbose_name_plural': 'Catalog Items (Products & Services)'},
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Physical Couture & Retail Product'), ('SERVICE', 'Bespoke Studio Service & Consultation')], db_index=True, default='PRODUCT', help_text='Extensible discriminator enabling coexistence of physical couture and appointment services', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='service_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes for bespoke appointment services or wellness consultations', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='business_profile',
            field=models.ForeignKey(help_text='Partner studio showroom offering this item', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.businessprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed material, fit, craft specifications, or service scope'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional promotional pricing', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(help_text='Primary high-resolution photography URI', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Product Title or Service Consultation Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Standard studio retail price (INR)', max_digits=12),
        ),
    ]
