# Generated by Django 6.0.7 on 2026-08-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='offer',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Feedback from admin moderation', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount or percentage', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Campaign expiration timestamp', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FLAT', 'Flat Discount'), ('SPECIAL', 'Special Offer'), ('ANNOUNCEMENT', 'Store Announcement')], default='PERCENTAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Campaign start timestamp', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
