# Generated by Django 6.1 on 2026-08-21 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_offer_discount_percentage_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of additional image URLs'),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Feedback from admin moderation', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HIDDEN', 'Hidden'), ('SUSPENDED', 'Suspended')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Sub-taxonomy classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_products', to='categories.category'),
        ),
    ]
