# Generated by Django 6.1 on 2026-09-21 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_additional_images_product_admin_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Campaign headline', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary text', max_length=200, null=True)),
                ('image_url', models.URLField(help_text='Cloud Storage URI for 16:9 banner', max_length=500)),
                ('promotion_type', models.CharField(choices=[('APP', 'Internal App Destination'), ('EXTERNAL', 'External URL')], default='APP', max_length=20)),
                ('internal_destination_type', models.CharField(blank=True, choices=[('STORE', 'Store / Showroom'), ('CATEGORY', 'Category'), ('OFFER', 'Offer')], help_text='Required if promotion_type is APP', max_length=20, null=True)),
                ('internal_destination_id', models.UUIDField(blank=True, help_text='UUID of the Store, Category, or Offer', null=True)),
                ('external_url', models.URLField(blank=True, help_text='Required if promotion_type is EXTERNAL', max_length=500, null=True)),
                ('start_at', models.DateTimeField(help_text='When the promotion becomes eligible for display')),
                ('end_at', models.DateTimeField(help_text='When the promotion expires')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='SCHEDULED', help_text='Administrative status. Affects display availability.', max_length=30)),
                ('priority', models.IntegerField(default=0, help_text='Lower number means higher display priority')),
                ('created_by', models.ForeignKey(help_text='Admin who created this promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Banner',
                'verbose_name_plural': 'Promotion Banners',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
