# Generated by Django 6.1 on 2026-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image_url',
            field=models.ImageField(help_text='Cloud Storage URI for 16:9 banner', max_length=500, upload_to='promotions/banners/'),
        ),
    ]
