# Generated by Django 6.0.7 on 2026-07-31 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Primary OTP login number', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Official account contact email', max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer (app_user)'), ('VENDOR', 'Partner Studio Owner (app_vendor)'), ('ADMIN', 'Staff Moderator & Governance (app_admin)'), ('SUPERADMIN', 'Platform Founder & Executive (app_admin)')], db_index=True, default='CUSTOMER', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this account is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates completed KYC or OTP phone verification')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates access to Django management admin site')),
                ('two_factor_secret', models.CharField(blank=True, help_text='Cryptographic 2FA secret token', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx')],
            },
        ),
    ]
