# Generated by Django 6.0.7 on 2026-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Customer display name', max_length=200, null=True),
        ),
    ]
