# Generated by Django 6.1 on 2026-10-06 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_name', models.CharField(help_text='The specific admin name used during login', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Login History',
                'verbose_name_plural': 'Admin Login Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
