# Generated by Django 6.1 on 2026-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='blocked_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='blocked_by_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
