# Generated by Django 6.0.7 on 2026-07-31 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(db_index=True, help_text='Official Brand or Studio Showroom Name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed narrative of studio specialty and offerings', null=True)),
                ('address_line_1', models.CharField(help_text='Street number, building, complex name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Floor, landmark, neighborhood', max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=20)),
                ('contact_email', models.EmailField(help_text='Public customer inquiry support email', max_length=254)),
                ('contact_phone', models.CharField(help_text='Public studio concierge or booking number', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude coordinates', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude coordinates', max_digits=10, null=True)),
                ('business_timings', models.JSONField(default=dict, help_text='Daily operation hour schedules (e.g. {"Monday": "10:00 - 20:00", "Saturday": "Closed"})')),
                ('logo_url', models.URLField(blank=True, help_text='Studio brand emblem logo URL', max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, help_text='Showroom header banner image URL', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(help_text='Partner vendor owning this showroom profile', on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
