# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary marketplace taxonomy category for this studio showroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms', to='categories.category'),
        ),
    ]
