# Generated by Django 6.0.7 on 2026-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessprofile_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='pincode',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='area',
            field=models.CharField(default='', help_text='Sub-locality or specific neighborhood zone', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
