# Generated by Django 6.0.7 on 2026-08-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_pincode_businessprofile_postal_code_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Specific subcategory for this studio showroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms_as_sub', to='categories.category'),
        ),
    ]
