# Generated by Django 6.0.7 on 2026-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_businessprofile_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Feedback or rejection reasons provided by admin', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='DRAFT', help_text='Current governance status of the store', max_length=20),
        ),
    ]
