# Generated by Django 6.1 on 2026-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessprofile_admin_remarks_businessprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='offers_home_service',
            field=models.BooleanField(default=False, help_text='Whether the studio offers home visits or services'),
        ),
    ]
